---
title: "HW4 - DATA 609"
author: "Thomas Hill"
date: "October 17, 2021"
output:
  html_document: default
  pdf_document: default
header-includes: -\usepackage{caption}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, library}

library(knitr)


```


__Ex. 1__ -- For Example 19 on Page 79 in the book, carry out the regression using R.



```{r, table-1}
x <- c(-0.98,  1.00,  2.02,  3.03 , 4.00)
y <- c(2.44,  -1.51,  -0.47,  2.54,  7.52)
ex_1 <- rbind(x,y)

knitr::kable(ex_1, formmat = 'latex')
```

__Ex. 2__ -- Implement the nonlinear curve-fitting of Example 20 on Page 83 for the following data:

```{r, table-2}
x <- c(0.10, 0.50, 1.00, 1.50, 2.00, 2.50)
y <- c(0.10, 0.28, 0.40, 0.40, 0.37, 0.32)
ex_2 <- rbind(x,y)

knitr::kable(ex_2, formmat = 'latex')
```




__Ex. 3__ --  For the data with binary _y_ values, try to fit the following data

```{r, table-3}
x <- c( 0.1,  0.5,  1.0,  1.5,  2.0,  2.5)
y <- c( 0,    0,    1,   1,    1,    0)
ex_3 <- rbind(x,y)

knitr::kable(ex_3, formmat = 'latex')
```


to the nonlinear function

$$ y = \frac{1}{1 + e^{ \alpha + \beta x}}$$,



starting with a = 1 and b = 1.







