---
title: "HW8 - DATA 609"
author: "Thomas Hill"
date: "December 12, 2021"
output:
  html_document: default
  pdf_document: default
header-includes: -\usepackage{caption}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, library}

library(nnet)
library(keras)
library(tensorflow)

```

__Ex. 1__ -- Use the _nnet_ package to analyze the _iris_ dataset. Use 80% of the 150 samples as the training data and the rest for validation. Discuss the results.


```{r,iris}

set.seed(1212)

train_index <- sample(seq_len(150), size =120) #generate random index separating iris into specified samples
train <- iris[train_index,] #training data
test <- iris[-train_index,] #test data

test_cat <- iris[-train_index, 5]  #true designations for test

iris_m <- nnet(formula = Species ~., data = iris, size = 1) #size is the number of units in the hidden layer


iris_predict <- predict(iris_m, test, type = 'class')


100*round(table(iris_predict, test_cat)/30,3)

```

Using only 1 hidden layer, the neural net model generated by nnet offers a very accurate model. 
